import { Body, Controller, Get, Patch, Post } from '@nestjs/common';
import { type User } from '@prisma/client';

import { CurrentUser } from '../common/decorators/current-user.decorator';
import { Public } from '../common/decorators/public.decorator';

import { UpdateUserDto } from './dto/update-user.dto';
import { type PublicUser, UsersService } from './users.service';

@Controller('users')
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Get('me')
  getMe(@CurrentUser() user: User): Promise<PublicUser | null> {
    return this.usersService.findById(user.id);
  }

  @Patch('me')
  updateMe(@CurrentUser() user: User, @Body() dto: UpdateUserDto): Promise<PublicUser> {
    return this.usersService.updateMe(user.id, dto);
  }

  // HIGH-04 (Audit-2): HMAC token required — prevents targeted email suppression attacks
  // Token generated by UsersService.generateUnsubscribeToken(email) when sending marketing emails
  @Public()
  @Post('unsubscribe')
  async unsubscribe(@Body('email') email: string, @Body('token') token: string) {
    return this.usersService.unsubscribe(email, token);
  }
}
